# Generated by Django 3.0.8 on 2020-08-17 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_auto_20200817_2040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diaryentry',
            options={'ordering': ['-dateTime']},
        ),
    ]
