# Generated by Django 3.0.8 on 2020-08-12 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='added',
            new_name='added_date',
        ),
    ]
